# Generated by Django 5.2.8 on 2025-11-06 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50)),
                ('response', models.CharField(blank=True, max_length=255)),
                ('ok', models.BooleanField(default=False)),
                ('port', models.CharField(blank=True, max_length=50)),
                ('baud', models.IntegerField(default=9600)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arduino_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='control_com_created_328dfd_idx'), models.Index(fields=['ok'], name='control_com_ok_4c249a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('port', models.CharField(blank=True, max_length=50)),
                ('baud', models.IntegerField(default=9600)),
                ('raw', models.TextField(blank=True)),
                ('ok', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captured_at'], name='control_sen_capture_e05907_idx'), models.Index(fields=['sensor'], name='control_sen_sensor_76fce5_idx'), models.Index(fields=['ok'], name='control_sen_ok_6a6d12_idx')],
            },
        ),
    ]
